### ISSUE TITLE
pretrained model RuntimeError

### ISSUE THREAD

**Issue by miraclerepuduce** [yamand16/ExposureCorrection#8]
Very stunning work. But I found a problem when I used the checkpoint you provided for testing.
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "E:\softwareyang\envs\pytorch_env3.10\lib\site-packages\torch\utils\data\dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "E:\softwareyang\envs\pytorch_env3.10\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\jinpengjuGrade22master\ExposureCorrection-main\test.py", line 41, in <module>
    for i, data in enumerate(dataset):
  File "E:\softwareyang\envs\pytorch_env3.10\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "E:\softwareyang\envs\pytorch_env3.10\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "E:\softwareyang\envs\pytorch_env3.10\lib\site-packages\torch\utils\data\dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "E:\softwareyang\envs\pytorch_env3.10\lib\site-packages\torch\utils\data\dataloader.py", line 1145, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 19580) exited unexpectedly

how to fix it?

thanks!!!

**Comment by Doku187** [comment]
Hi there, I'm also suffering from the same issue.. did you possibly find a solution?

I'm thinking it might be caused by the python version (im using 3.8). I'll try testing on an older version.
